import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFFFF" },
  appContent: { flex: 1 },
  hiddenCamera: { position: "absolute", width: 1, height: 1 },
  centerTextContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#FFFFFF",
  },
  permissionText: {
    textAlign: "center",
    color: "#1C1C1E",
    fontSize: 15,
    marginBottom: 20,
  },
  permissionBtn: {
    paddingHorizontal: 24,
    paddingVertical: 13,
    borderRadius: 25,
    backgroundColor: "#FFC700",
  },
  permissionBtnText: { fontWeight: "700", color: "#111111" },

  header: {
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerEyebrow: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 1.6,
    marginBottom: 2,
  },
  headerTitle: { fontSize: 26, fontWeight: "700", color: "#18181B" },
  headerStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: "#F4F4F5",
  },
  headerStatusText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#71717A",
    letterSpacing: 1,
  },

  modeSwitcher: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginTop: 10,
    padding: 5,
    borderRadius: 20,
    backgroundColor: "#F4F4F5",
    gap: 5,
  },
  modeButton: {
    flex: 1,
    height: 45,
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 7,
  },
  modeButtonActive: { backgroundColor: "#FFC700" },
  modeButtonText: { fontSize: 12, fontWeight: "700", color: "#71717A" },
  modeButtonTextActive: { color: "#111111" },

  mainArea: { flex: 1 },

  flashlightScreen: { flex: 1, justifyContent: "center", alignItems: "center" },
  flashlightButtonArea: {
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
  },
  rippleContainer: {
    position: "absolute",
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
  },
  ripple: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: 85,
    backgroundColor: "#FFEB60",
  },
  powerButton: {
    width: 170,
    height: 170,
    borderRadius: 85,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#E5E5EA",
    borderWidth: 1,
    borderColor: "#D1D1D6",
  },
  powerButtonActive: {
    backgroundColor: "#FFC700",
    borderColor: "#E6B200",
    shadowColor: "#FFC700",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  flashlightHint: {
    marginTop: 16,
    fontSize: 12,
    color: "#A1A1AA",
    fontWeight: "600",
  },

  morseScreen: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 2,
  },
  divider: { height: 1, backgroundColor: "#F4F4F5", marginVertical: 18 },
  messageCard: {
    backgroundColor: "#FAFAFA",
    borderWidth: 1,
    borderColor: "#E4E4E7",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
  },
  messageCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  messageLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 1.2,
  },
  characterCounter: { fontSize: 10, fontWeight: "700", color: "#A1A1AA" },
  morseInput: {
    marginTop: 8,
    height: 40,
    fontSize: 18,
    fontWeight: "600",
    color: "#18181B",
  },

  quickMessageRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
  },
  quickMessageButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: "#F4F4F5",
    borderWidth: 1,
    borderColor: "#E4E4E7",
  },
  quickMessageButtonActive: {
    backgroundColor: "#FFC700",
    borderColor: "#FFC700",
  },
  quickMessageText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#71717A",
    letterSpacing: 0.5,
  },
  quickMessageTextActive: { color: "#111111" },

  speedSection: { paddingHorizontal: 4 },
  speedLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 1.1,
    marginBottom: 10,
  },
  speedRow: { flexDirection: "row", gap: 8 },
  speedButton: {
    flex: 1,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F4F5",
    borderWidth: 1,
    borderColor: "#E4E4E7",
  },
  speedButtonActive: { backgroundColor: "#FFC700", borderColor: "#FFC700" },
  speedButtonText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#71717A",
    letterSpacing: 0.4,
  },
  speedButtonTextActive: { color: "#111111" },

  translationSection: {
    paddingHorizontal: 4,
    height: 100,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 1.2,
  },
  signalStatus: { flexDirection: "row", alignItems: "center", gap: 5 },
  signalDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: "#22C55E",
  },
  signalStatusText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 0.5,
  },
  nakedTranslationArea: {
    minHeight: 80,
    justifyContent: "center",
    paddingVertical: 10,
    alignItems: "center",
  },
  morseCharactersRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  morseCharacter: {
    minWidth: 42,
    paddingHorizontal: 8,
    paddingVertical: 7,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E4E4E7",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  morseCharacterActive: {
    backgroundColor: "#FFC700",
    borderColor: "#E6B200",
    transform: [{ scale: 1.08 }],
    shadowColor: "#FFC700",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 4,
  },
  morseCharacterText: { fontSize: 14, fontWeight: "800", color: "#18181B" },
  morseCharacterTextActive: { color: "#111111" },
  morseCodeText: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
    color: "#71717A",
    letterSpacing: 0.7,
  },
  morseCodeTextActive: { color: "#111111" },
  emptyTranslationText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#A1A1AA",
    textAlign: "center",
  },

  liveSignalArea: {
    height: 120,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  liveSignalGlow: {
    position: "absolute",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#22C55E",
  },
  liveSignalCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F4F4F5",
    borderWidth: 2,
    borderColor: "#E4E4E7",
  },
  liveSignalCircleActive: {
    borderColor: "#22C55E",
  },
  liveSignalInner: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#D4D4D8",
    marginBottom: 3,
  },
  liveSignalInnerOn: {
    backgroundColor: "#22C55E",
  },
  liveSignalLabel: {
    fontSize: 8,
    fontWeight: "900",
    color: "#71717A",
    letterSpacing: 1,
  },

  transmitButton: {
    height: 52,
    borderRadius: 17,
    backgroundColor: "#FFC700",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 9,
  },
  transmitButtonDisabled: { backgroundColor: "#E4E4E7" },
  transmitButtonText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#111111",
    letterSpacing: 0.5,
    bottom: 0,
  },

  sliderSection: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 12 },
  sliderHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  sliderTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  sliderTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A1A1AA",
    letterSpacing: 0.8,
  },
  sliderValue: { fontSize: 12, fontWeight: "800", color: "#18181B" },
  sliderTrack: {
    height: 34,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sliderTick: {
    width: 3,
    height: 20,
    borderRadius: 2,
    backgroundColor: "#E4E4E7",
  },
  sliderTickActive: { backgroundColor: "#FFC700" },

  bannerContainer: {
    minHeight: 62,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#F4F4F5",
  },
});
